package GUOLD;

import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;

import net.minecraft.creativetab.CreativeTabs;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.common.config.Configuration;
import GUOLD.info.Reference;
import GUOLD.info.Variables;
import GUOLD.proxy.CommonProxy;
import GUOLD.worldGen.RetroGenManager;
import GUOLD.worldGen.WorldGenBlockAirCrystalOre;
import GUOLD.worldGen.WorldGenBlockEarthCrystalOre;
import GUOLD.worldGen.WorldGenBlockEnergyCrystalOre;
import GUOLD.worldGen.WorldGenBlockFalseBlock;
import GUOLD.worldGen.WorldGenBlockFireCrystalOre;
import GUOLD.worldGen.WorldGenBlockGarnetOre;
import GUOLD.worldGen.WorldGenBlockWaterCrystalOre;
import cpw.mods.fml.common.FMLLog;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkRegistry;
import cpw.mods.fml.common.registry.GameRegistry;

@Mod(modid = Reference.MODDID, name = Reference.NAME, version = Reference.VERSION)
public final class GearUtilities {
    
    @Instance(Reference.MODDID)
    public static GearUtilities instance;
    
    public static Logger logger = Logger.getLogger(Reference.MODDID);
    
    @SidedProxy(clientSide = Reference.CLIENT_PROXY, serverSide = Reference.COMMON_PROXY)
    public static CommonProxy proxy;
    
    public static CreativeTabs tabGUBlocks = new GUCreativeTab(Reference.NAME + ": Blocks");
    public static CreativeTabs tabGUItems = new GUCreativeTab(Reference.NAME + ": Items");
    public static CreativeTabs tabGUFluids = new GUCreativeTab(Reference.NAME + ": Fluids");
    
//    @EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        
        instance = this;
        // logger.setParent(FMLLog.getLogger());
        
        Configuration config = new Configuration(event.getSuggestedConfigurationFile());
        config.load();
        Variables.updateVariables(config);
        ItemRegistry.init(config);
        BlockRegistry.init(config);
        FluidRegistry.initFluids();
        RetroGenManager.init();
        EntityRegistry.init();
        MultiRegistry.init();
        
        MinecraftForge.EVENT_BUS.register(new ForgeEvents());
        GameRegistry.registerFuelHandler(new GUFuelHandler());
        
        ModMetadata metadata = event.getModMetadata();
        metadata.autogenerated = false;
        metadata.authorList = Arrays.asList("ASB2");
        metadata.description = "A mod from ASB2 to ASB2";
        metadata.logoFile = Reference.MODDID + ":assets/" + Reference.MODDID + "/banner.png";
        
        config.save();
    }
    
//    @EventHandler
    public void mainInit(FMLInitializationEvent event) {
        
        proxy.register();
        
        // NetworkRegistry.instance().registerGuiHandler(this,
        // GearUtilities.proxy);
        // MinecraftForge.addGrassPlant(BlockRegistry.BlockBurningFlower, 0,
        // 100);
        // MinecraftForge.addGrassPlant(BlockRegistry.BlockFreezingFlower, 0,
        // 100);
        GameRegistry.registerWorldGenerator(new WorldGenBlockAirCrystalOre(), 0);
        GameRegistry.registerWorldGenerator(new WorldGenBlockEarthCrystalOre(), 0);
        GameRegistry.registerWorldGenerator(new WorldGenBlockFireCrystalOre(), 0);
        GameRegistry.registerWorldGenerator(new WorldGenBlockWaterCrystalOre(), 0);
        // GameRegistry.registerWorldGenerator(new
        // WorldGenBlockFreezingFlower());
        // GameRegistry.registerWorldGenerator(new
        // WorldGenBlockBurningFlower());
        GameRegistry.registerWorldGenerator(new WorldGenBlockEnergyCrystalOre(), 0);
        GameRegistry.registerWorldGenerator(new WorldGenBlockGarnetOre(), 0);
        GameRegistry.registerWorldGenerator(new WorldGenBlockFalseBlock(), 0);
        // OreDictionary.registerOre("bioMass", Item.seeds);
        // GameRegistry.registerWorldGenerator(new
        // WorldGenBlockAirCrystalOre());
        // GameRegistry.registerPlayerTracker(new TechCraftPlayerTracker ());
        // MinecraftForge.EVENT_BUS.register(new TechCraftForgeEvents());
    }
    
//    @EventHandler
    public void postInit(FMLPostInitializationEvent event) {
        FluidRegistry.registerFluidContainers();
        CraftRegistry.init();
        // WhiteLists.getInstance().addWrench(new
        // ItemStack(ItemRegistry.ItemAdvancedStick));
    }
    
    public static void log(String message) {
        logger.log(Level.INFO, message);
    }
}
